#Current verse
msg.currentVerse=Hazırki ayə

#Could not connect to server
msg.errorConnect=Serverə qoşulmaq mümkün olmadı

#Error - Empty text
msg.errorContIsEmpty=Xəta - Boş mətn

#Error - Very large text
msg.errorContVeryLarge=Xəta - Mətndə çox uzun

#Invalid File: {0}
msg.errorInvalidFile=Yanlış Fayl: {0}

#Error - Try again
msg.errorTryAgain=Xəta - Yenidən cəhd edin

#Exact phrase
msg.exactFrase=Dəqiq ifadə

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Mesaj göndərildi!\nTəklifinizi nəzərdən keçirəcəyik.\nTəşəkkür edirik.

#Results: {0}
msg.results_x=Nəticələr: {0}

#Sort by
msg.sortBy=Sıralamaq üçün

#Suggested edition
msg.suggestedEdition=Təklif olunan redaktə

#Double-click to select
msg.toolTipTextJListResult=Seçmək üçün iki dəfə klikləyin

#Type your search here...
msg.toolTipTextJText=Axtarışınızı buraya daxil edin...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Tam Söz

#List: 
VerseSearchPanel.jLabelList.text=Siyahıya alma: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Bütün Müqəddəs Kitab

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Bütün sözlər

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Hər hansı bir söz

#Book:
VerseSearchPanel.jRadioButtonBook.text=Kitab:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Yeni Əhdi-Cədid

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Köhnə Əhdi-Cədid

#Cancel
word.cancel=Ləğv et

#Error
word.error=Xəta

#Help
word.help=Kömək

#Home
word.home=Başlanğıc

#Natural
word.natural=Təbii

#Relevance
word.relevance=Əhəmiyyət

#Report Error
word.reportError=Xətanı bildirin

#Search
word.search=Axtarış

#Searching...
word.searching=Axtarılır...

#Send
word.send=Göndər

#Waiting...
word.waiting___=Gözlənilir...