#Current verse
msg.currentVerse=বর্তমান শ্লোক

#Could not connect to server
msg.errorConnect=সার্ভারের সাথে সংযোগ স্থাপন করা সম্ভব হয়নি

#Error - Empty text
msg.errorContIsEmpty=ত্রুটি - খালি টেক্সট

#Error - Very large text
msg.errorContVeryLarge=ত্রুটি - টেক্সট খুব বড়

#Invalid File: {0}
msg.errorInvalidFile=অবৈধ ফাইল: {0}

#Error - Try again
msg.errorTryAgain=ত্রুটি - আবার চেষ্টা করুন

#Exact phrase
msg.exactFrase=সঠিক বাক্য

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=বার্তা পাঠানো হয়েছে!\nআমরা আপনার প্রস্তাবটি পর্যালোচনা করব।\nধন্যবাদ।

#Results: {0}
msg.results_x=ফলাফল: {0}

#Sort by
msg.sortBy=অনুসারে সাজান

#Suggested edition
msg.suggestedEdition=প্রস্তাবিত সম্পাদনা

#Double-click to select
msg.toolTipTextJListResult=নির্বাচনের জন্য ডাবল ক্লিক করুন

#Type your search here...
msg.toolTipTextJText=এখানে আপনার অনুসন্ধান লিখুন...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=সম্পূর্ণ শব্দ

#List: 
VerseSearchPanel.jLabelList.text=তালিকা: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=সমস্ত বাইবেল

#All words
VerseSearchPanel.jRadioButtonAllWords.text=সমস্ত শব্দ

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=যেকোনো শব্দ

#Book:
VerseSearchPanel.jRadioButtonBook.text=বই:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=নতুন নিয়ম

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=পুরাতন নিয়ম

#Cancel
word.cancel=বাতিল করুন

#Error
word.error=ত্রুটি

#Help
word.help=সাহায্য

#Home
word.home=শুরু

#Natural
word.natural=প্রাকৃতিক

#Relevance
word.relevance=প্রাসঙ্গিকতা

#Report Error
word.reportError=ত্রুটি রিপোর্ট করুন

#Search
word.search=অনুসন্ধান

#Searching...
word.searching=অনুসন্ধান করা হচ্ছে...

#Send
word.send=পাঠান

#Waiting...
word.waiting___=অপেক্ষা করা হচ্ছে...