#Current verse
msg.currentVerse=Aktueller Vers

#Could not connect to server
msg.errorConnect=Verbindung zum Server konnte nicht hergestellt werden

#Error - Empty text
msg.errorContIsEmpty=Fehler - Leerer Text

#Error - Very large text
msg.errorContVeryLarge=Fehler - Text zu groß

#Invalid File: {0}
msg.errorInvalidFile=Ungültige Datei: {0}

#Error - Try again
msg.errorTryAgain=Fehler - Bitte erneut versuchen

#Exact phrase
msg.exactFrase=Genauer Satz

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Nachricht gesendet!\nWir werden Ihren Vorschlag prüfen.\nDanke.

#Results: {0}
msg.results_x=Ergebnisse: {0}

#Sort by
msg.sortBy=Sortieren nach

#Suggested edition
msg.suggestedEdition=Vorgeschlagene Bearbeitung

#Double-click to select
msg.toolTipTextJListResult=Doppelklick zum Auswählen

#Type your search here...
msg.toolTipTextJText=Geben Sie hier Ihre Suche ein...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Vollständiges Wort

#List: 
VerseSearchPanel.jLabelList.text=Auflisten: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Die ganze Bibel

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Alle Wörter

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Jedes Wort

#Book:
VerseSearchPanel.jRadioButtonBook.text=Buch:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Neues Testament

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Altes Testament

#Cancel
word.cancel=Abbrechen

#Error
word.error=Fehler

#Help
word.help=Hilfe

#Home
word.home=Start

#Natural
word.natural=Natürlich

#Relevance
word.relevance=Relevanz

#Report Error
word.reportError=Fehler melden

#Search
word.search=Suche

#Searching...
word.searching=Suche läuft...

#Send
word.send=Senden

#Waiting...
word.waiting___=Warten...