#Current verse
msg.currentVerse=Versículo actual

#Could not connect to server
msg.errorConnect=No se pudo conectar al servidor

#Error - Empty text
msg.errorContIsEmpty=Error - Texto vacío

#Error - Very large text
msg.errorContVeryLarge=Error - Texto muy grande

#Invalid File: {0}
msg.errorInvalidFile=Archivo Inválido: {0}

#Error - Try again
msg.errorTryAgain=Error - Inténtelo de nuevo

#Exact phrase
msg.exactFrase=Frase exacta

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=¡Mensaje enviada!\nVamos a analizar su sugerencia.\nGracias.

#Results: {0}
msg.results_x=Resultados: {0}

#Sort by
msg.sortBy=Ordenar por

#Suggested edition
msg.suggestedEdition=Edición sugerida

#Double-click to select
msg.toolTipTextJListResult=Haga doble clic para seleccionar

#Type your search here...
msg.toolTipTextJText=Escribe su búsqueda aquí...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Palabra entera

#List: 
VerseSearchPanel.jLabelList.text=Listar: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Toda la Biblia

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Todas las palabras

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Cualquier palabra

#Book:
VerseSearchPanel.jRadioButtonBook.text=Libro:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Nuevo Testamento

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Antiguo Testamento

#Cancel
word.cancel=Cancelar

#Error
word.error=Error

#Help
word.help=Ayuda

#Home
word.home=Inicio

#Natural
word.natural=Natural

#Relevance
word.relevance=Relevancia

#Report Error
word.reportError=Reportar Error

#Search
word.search=Buscar

#Searching...
word.searching=Buscando...

#Send
word.send=Enviar

#Waiting...
word.waiting___=Espera...