#Current verse
msg.currentVerse=Verset actuel

#Could not connect to server
msg.errorConnect=Impossible de se connecter au serveur

#Error - Empty text
msg.errorContIsEmpty=Erreur - Texte vide

#Error - Very large text
msg.errorContVeryLarge=Erreur - Texte trop grand

#Invalid File: {0}
msg.errorInvalidFile=Fichier non valide: {0}

#Error - Try again
msg.errorTryAgain=Erreur - Réessayer

#Exact phrase
msg.exactFrase=Phrase exacte

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Message envoyé!\nNous examinerons votre suggestion.\nMerci.

#Results: {0}
msg.results_x=Résultats: {0}

#Sort by
msg.sortBy=Trier par

#Suggested edition
msg.suggestedEdition=Modification suggérée

#Double-click to select
msg.toolTipTextJListResult=Double-clic pour sélectionner

#Type your search here...
msg.toolTipTextJText=Tapez votre recherche ici ...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Mot entier

#List: 
VerseSearchPanel.jLabelList.text=Liste: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Toute la Bible

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Tous les mots

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=N'importe quel mot

#Book:
VerseSearchPanel.jRadioButtonBook.text=Livre:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Nouveau Testament

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Ancien Testament

#Cancel
word.cancel=Annuler

#Error
word.error=Erreur

#Help
word.help=Aide

#Home
word.home=Accueil

#Natural
word.natural=Naturel

#Relevance
word.relevance=Pertinence

#Report Error
word.reportError=Signaler une erreur

#Search
word.search=Recherche

#Searching...
word.searching=En train de chercher...

#Send
word.send=Envoyer

#Waiting...
word.waiting___=En train d'attendre...