#Current verse
msg.currentVerse=वर्तमान पद

#Could not connect to server
msg.errorConnect=सर्वर से कनेक्ट नहीं हो सका

#Error - Empty text
msg.errorContIsEmpty=त्रुटि - पाठ खाली है

#Error - Very large text
msg.errorContVeryLarge=त्रुटि - पाठ बहुत बड़ा है

#Invalid File: {0}
msg.errorInvalidFile=अमान्य फ़ाइल: {0}

#Error - Try again
msg.errorTryAgain=त्रुटि - फिर से प्रयास करें

#Exact phrase
msg.exactFrase=सटीक वाक्यांश

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=संदेश भेजा गया!\nहम आपकी सुझाव का विश्लेषण करेंगे।\nधन्यवाद।

#Results: {0}
msg.results_x=परिणाम: {0}

#Sort by
msg.sortBy=द्वारा क्रमबद्ध करें

#Suggested edition
msg.suggestedEdition=सुझाई गई संपादन

#Double-click to select
msg.toolTipTextJListResult=चुनने के लिए डबल क्लिक करें

#Type your search here...
msg.toolTipTextJText=यहाँ अपनी खोज टाइप करें...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=पूर्ण शब्द

#List: 
VerseSearchPanel.jLabelList.text=सूचीबद्ध करें: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=पूरी बाइबिल

#All words
VerseSearchPanel.jRadioButtonAllWords.text=सभी शब्द

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=कोई भी शब्द

#Book:
VerseSearchPanel.jRadioButtonBook.text=पुस्तक:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=नया नियम

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=पुराना नियम

#Cancel
word.cancel=रद्द करें

#Error
word.error=त्रुटि

#Help
word.help=सहायता

#Home
word.home=शुरुआत

#Natural
word.natural=स्वाभाविक

#Relevance
word.relevance=प्रासंगिकता

#Report Error
word.reportError=त्रुटि रिपोर्ट करें

#Search
word.search=खोज

#Searching...
word.searching=खोज रहे हैं...

#Send
word.send=भेजें

#Waiting...
word.waiting___=प्रतीक्षा कर रहा...