#Current verse
msg.currentVerse=Jelenlegi vers

#Could not connect to server
msg.errorConnect=Nem sikerült csatlakozni a szerverhez

#Error - Empty text
msg.errorContIsEmpty=Hiba - Üres szöveg

#Error - Very large text
msg.errorContVeryLarge=Hiba - Túl nagy szöveg

#Invalid File: {0}
msg.errorInvalidFile=Érvénytelen fájl: {0}

#Error - Try again
msg.errorTryAgain=Hiba - Kérjük, próbálja újra

#Exact phrase
msg.exactFrase=Pontosan így

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Üzenet elküldve!\nMeg fogjuk vizsgálni a javaslatát.\nKöszönjük.

#Results: {0}
msg.results_x=Eredmények: {0}

#Sort by
msg.sortBy=Rendezés szerint

#Suggested edition
msg.suggestedEdition=Javasolt szerkesztés

#Double-click to select
msg.toolTipTextJListResult=Kattintson duplán a kiválasztáshoz

#Type your search here...
msg.toolTipTextJText=Írja be a keresését ide...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Teljes szó

#List: 
VerseSearchPanel.jLabelList.text=Lista: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Teljes Biblia

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Minden szó

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Bármely szó

#Book:
VerseSearchPanel.jRadioButtonBook.text=Könyv:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Új Szövetség

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Régi Szövetség

#Cancel
word.cancel=Mégse

#Error
word.error=Hiba

#Help
word.help=Segítség

#Home
word.home=Kezdőlap

#Natural
word.natural=Természetes

#Relevance
word.relevance=Relevancia

#Report Error
word.reportError=Hiba bejelentése

#Search
word.search=Keresés

#Searching...
word.searching=Keresés...

#Send
word.send=Küldés

#Waiting...
word.waiting___=Várakozás...