#Current verse
msg.currentVerse=Ayat saat ini

#Could not connect to server
msg.errorConnect=Tidak dapat terhubung ke server

#Error - Empty text
msg.errorContIsEmpty=Kesalahan - Teks kosong

#Error - Very large text
msg.errorContVeryLarge=Kesalahan - Teks terlalu besar

#Invalid File: {0}
msg.errorInvalidFile=File Tidak Valid: {0}

#Error - Try again
msg.errorTryAgain=Kesalahan - Coba lagi

#Exact phrase
msg.exactFrase=Frasa tepat

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Pesan terkirim!\nKami akan menganalisis saran Anda.\nTerima kasih.

#Results: {0}
msg.results_x=Hasil: {0}

#Sort by
msg.sortBy=Urutkan berdasarkan

#Suggested edition
msg.suggestedEdition=Suntingan yang disarankan

#Double-click to select
msg.toolTipTextJListResult=Klik dua kali untuk memilih

#Type your search here...
msg.toolTipTextJText=Ketik pencarian Anda di sini...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Kata Utuh

#List: 
VerseSearchPanel.jLabelList.text=Daftar: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Seluruh Alkitab

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Semua kata

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Kata apa saja

#Book:
VerseSearchPanel.jRadioButtonBook.text=Buku:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Perjanjian Baru

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Perjanjian Lama

#Cancel
word.cancel=Batalkan

#Error
word.error=Kesalahan

#Help
word.help=Bantuan

#Home
word.home=Beranda

#Natural
word.natural=Alami

#Relevance
word.relevance=Relevansi

#Report Error
word.reportError=Laporkan Kesalahan

#Search
word.search=Pencarian

#Searching...
word.searching=Mencari...

#Send
word.send=Kirim

#Waiting...
word.waiting___=Menunggu...