#Current verse
msg.currentVerse=Corrente verse

#Could not connect to server
msg.errorConnect=Impossibile connettersi al server

#Error - Empty text
msg.errorContIsEmpty=Errore - Testo vuoto

#Error - Very large text
msg.errorContVeryLarge=Errore - Testo troppo lungo

#Invalid File: {0}
msg.errorInvalidFile=File non valido: {0}

#Error - Try again
msg.errorTryAgain=Errore - Riprova

#Exact phrase
msg.exactFrase=Frase esatta

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Messaggio inviato!\nEsamineremo il tuo suggerimento.\nGrazie.

#Results: {0}
msg.results_x=Risultati: {0}

#Sort by
msg.sortBy=Ordina per

#Suggested edition
msg.suggestedEdition=Modifica suggerita

#Double-click to select
msg.toolTipTextJListResult=Doppio clic per selezionare

#Type your search here...
msg.toolTipTextJText=Digita la tua ricerca qui...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Parola Intera

#List: 
VerseSearchPanel.jLabelList.text=Lista: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Tutta la Bibbia

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Tutte le parole

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Qualsiasi parola

#Book:
VerseSearchPanel.jRadioButtonBook.text=Libro:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Nuovo Testamento

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Antico Testamento

#Cancel
word.cancel=Cancellare

#Error
word.error=Errore

#Help
word.help=Aiuto

#Home
word.home=Home

#Natural
word.natural=Naturale

#Relevance
word.relevance=Rilevanza

#Report Error
word.reportError=Segnalare errore

#Search
word.search=Ricerca

#Searching...
word.searching=Ricerca in corso...

#Send
word.send=Inviare

#Waiting...
word.waiting___=Aspetta ...