#Current verse
msg.currentVerse=電流節

#Could not connect to server
msg.errorConnect=サーバーに接続できませんでした

#Error - Empty text
msg.errorContIsEmpty=エラー - 空のテキスト

#Error - Very large text
msg.errorContVeryLarge=エラー - 非常に大きなテキスト

#Invalid File: {0}
msg.errorInvalidFile=無効なファイル：{0}

#Error - Try again
msg.errorTryAgain=エラー - もう一度やり直してください

#Exact phrase
msg.exactFrase=正確な句

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=送信されたメッセージ！\n私たちはあなたの提案を検討します。\nありがとう....

#Results: {0}
msg.results_x=結果：{0}

#Sort by
msg.sortBy=並び替え

#Suggested edition
msg.suggestedEdition=推奨版

#Double-click to select
msg.toolTipTextJListResult=ダブルクリックして選択します

#Type your search here...
msg.toolTipTextJText=ここに検索を入力してください...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=単語全体

#List: 
VerseSearchPanel.jLabelList.text=リスト: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=すべての聖書

#All words
VerseSearchPanel.jRadioButtonAllWords.text=すべての単語

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=任意の単語

#Book:
VerseSearchPanel.jRadioButtonBook.text=本：

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=新約聖書

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=旧約聖書

#Cancel
word.cancel=キャンセル

#Error
word.error=エラー

#Help
word.help=ヘルプ

#Home
word.home=家

#Natural
word.natural=自然

#Relevance
word.relevance=関連性

#Report Error
word.reportError=エラーを報告します

#Search
word.search=検索

#Searching...
word.searching=検索...

#Send
word.send=送信

#Waiting...
word.waiting___=待っている...