#Current verse
msg.currentVerse=현재 구절

#Could not connect to server
msg.errorConnect=서버에 연결할 수 없습니다

#Error - Empty text
msg.errorContIsEmpty=오류 - 빈 텍스트

#Error - Very large text
msg.errorContVeryLarge=오류 - 텍스트가 너무 큽니다

#Invalid File: {0}
msg.errorInvalidFile=잘못된 파일: {0}

#Error - Try again
msg.errorTryAgain=오류 - 다시 시도하십시오

#Exact phrase
msg.exactFrase=정확한 문구

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=메시지가 전송되었습니다!\n귀하의 제안을 검토하겠습니다.\n감사합니다.

#Results: {0}
msg.results_x=결과: {0}

#Sort by
msg.sortBy=정렬 기준

#Suggested edition
msg.suggestedEdition=제안된 편집

#Double-click to select
msg.toolTipTextJListResult=선택하려면 두 번 클릭하세요

#Type your search here...
msg.toolTipTextJText=여기에 검색어를 입력하세요...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=전체 단어

#List: 
VerseSearchPanel.jLabelList.text=목록: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=전체 성경

#All words
VerseSearchPanel.jRadioButtonAllWords.text=모든 단어

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=모든 단어

#Book:
VerseSearchPanel.jRadioButtonBook.text=책:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=신약

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=구약

#Cancel
word.cancel=취소

#Error
word.error=오류

#Help
word.help=도움말

#Home
word.home=시작

#Natural
word.natural=자연스러운

#Relevance
word.relevance=관련성

#Report Error
word.reportError=오류 신고

#Search
word.search=검색

#Searching...
word.searching=검색 중...

#Send
word.send=전송

#Waiting...
word.waiting___=대기 중...