#Current verse
msg.currentVerse=Ayat semasa

#Could not connect to server
msg.errorConnect=Tidak dapat menyambung ke pelayan

#Error - Empty text
msg.errorContIsEmpty=Ralat - Teks kosong

#Error - Very large text
msg.errorContVeryLarge=Ralat - Teks terlalu besar

#Invalid File: {0}
msg.errorInvalidFile=Fail Tidak Sah: {0}

#Error - Try again
msg.errorTryAgain=Ralat - Sila cuba lagi

#Exact phrase
msg.exactFrase=Frasa tepat

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Mesej dihantar!\nKami akan menganalisis cadangan anda.\nTerima kasih.

#Results: {0}
msg.results_x=Keputusan: {0}

#Sort by
msg.sortBy=Susun mengikut

#Suggested edition
msg.suggestedEdition=Penyuntingan dicadangkan

#Double-click to select
msg.toolTipTextJListResult=Klik dua kali untuk memilih

#Type your search here...
msg.toolTipTextJText=Masukkan carian anda di sini...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Kata Penuh

#List: 
VerseSearchPanel.jLabelList.text=Senarai: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Seluruh Alkitab

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Semua perkataan

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Mana-mana perkataan

#Book:
VerseSearchPanel.jRadioButtonBook.text=Buku:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Perjanjian Baru

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Perjanjian Lama

#Cancel
word.cancel=Batal

#Error
word.error=Ralat

#Help
word.help=Bantuan

#Home
word.home=Mula

#Natural
word.natural=Semula jadi

#Relevance
word.relevance=Kepentingan

#Report Error
word.reportError=Laporkan Ralat

#Search
word.search=Carian

#Searching...
word.searching=Mencari...

#Send
word.send=Hantar

#Waiting...
word.waiting___=Menunggu...