#Current verse
msg.currentVerse=Huidig ​​vers

#Could not connect to server
msg.errorConnect=Kon geen verbinding maken met de server

#Error - Empty text
msg.errorContIsEmpty=Fout - lege tekst

#Error - Very large text
msg.errorContVeryLarge=Fout - Hele grote tekst

#Invalid File: {0}
msg.errorInvalidFile=Ongeldig bestand: {0}

#Error - Try again
msg.errorTryAgain=Fout - probeer het opnieuw

#Exact phrase
msg.exactFrase=Exacte zin

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Bericht verzonden!\nWe zullen uw suggestie bekijken.\nBedankt....

#Results: {0}
msg.results_x=Resultaten: {0}

#Sort by
msg.sortBy=Sorteer op

#Suggested edition
msg.suggestedEdition=Aanbevolen editie

#Double-click to select
msg.toolTipTextJListResult=Dubbelklik om te selecteren

#Type your search here...
msg.toolTipTextJText=Typ hier uw zoekopdracht ...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Hele woord

#List: 
VerseSearchPanel.jLabelList.text=Lijst: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Hele bijbel

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Alle woorden

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Elk woord

#Book:
VerseSearchPanel.jRadioButtonBook.text=Boek:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Nieuwe Testament

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Oude Testament

#Cancel
word.cancel=Annuleren

#Error
word.error=Fout

#Help
word.help=Help

#Home
word.home=Home

#Natural
word.natural=Normaal

#Relevance
word.relevance=Relevantie

#Report Error
word.reportError=Fout melden

#Search
word.search=Zoek

#Searching...
word.searching=Zoeken...

#Send
word.send=Versturen

#Waiting...
word.waiting___=Aan het wachten...