#Current verse
msg.currentVerse=Aktualny werset

#Could not connect to server
msg.errorConnect=Nie można połączyć z serwerem

#Error - Empty text
msg.errorContIsEmpty=Błąd - Pusty tekst

#Error - Very large text
msg.errorContVeryLarge=Błąd - Zbyt duży tekst

#Invalid File: {0}
msg.errorInvalidFile=Nieprawidłowy plik: {0}

#Error - Try again
msg.errorTryAgain=Błąd - Spróbuj ponownie

#Exact phrase
msg.exactFrase=Dokładne zdanie

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Wiadomość wysłana!\nPrzeanalizujemy Twoją sugestię.\nDziękuję.

#Results: {0}
msg.results_x=Wyniki: {0}

#Sort by
msg.sortBy=Sortuj według

#Suggested edition
msg.suggestedEdition=Sugerowana edycja

#Double-click to select
msg.toolTipTextJListResult=Kliknij dwukrotnie, aby wybrać

#Type your search here...
msg.toolTipTextJText=Wpisz swoje wyszukiwanie tutaj...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Całe słowo

#List: 
VerseSearchPanel.jLabelList.text=Lista: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Cała Biblia

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Wszystkie słowa

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Jakiekolwiek słowo

#Book:
VerseSearchPanel.jRadioButtonBook.text=Księga:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Nowy Testament

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Stary Testament

#Cancel
word.cancel=Anuluj

#Error
word.error=Błąd

#Help
word.help=Pomoc

#Home
word.home=Początek

#Natural
word.natural=Naturalny

#Relevance
word.relevance=Relewancja

#Report Error
word.reportError=Zgłoś błąd

#Search
word.search=Wyszukiwanie

#Searching...
word.searching=Szukam...

#Send
word.send=Wyślij

#Waiting...
word.waiting___=Czekam...