#Current verse
msg.currentVerse=Versetul curent

#Could not connect to server
msg.errorConnect=Nu s-a putut conecta la server

#Error - Empty text
msg.errorContIsEmpty=Eroare - Text gol

#Error - Very large text
msg.errorContVeryLarge=Eroare - Text prea mare

#Invalid File: {0}
msg.errorInvalidFile=Fișier invalid: {0}

#Error - Try again
msg.errorTryAgain=Eroare - Încercați din nou

#Exact phrase
msg.exactFrase=Fraza exactă

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Mesaj trimis!\nVom analiza sugestia dumneavoastră.\nMulțumesc.

#Results: {0}
msg.results_x=Rezultate: {0}

#Sort by
msg.sortBy=Sortează după

#Suggested edition
msg.suggestedEdition=Editare sugerată

#Double-click to select
msg.toolTipTextJListResult=Faceți dublu clic pentru a selecta

#Type your search here...
msg.toolTipTextJText=Introduceți căutarea aici...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Cuvânt întreg

#List: 
VerseSearchPanel.jLabelList.text=Lista: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Toată Biblia

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Toate cuvintele

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Orice cuvânt

#Book:
VerseSearchPanel.jRadioButtonBook.text=Carte:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Noul Testament

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Vechiul Testament

#Cancel
word.cancel=Anulați

#Error
word.error=Eroare

#Help
word.help=Ajutor

#Home
word.home=Acasă

#Natural
word.natural=Natural

#Relevance
word.relevance=Relevanță

#Report Error
word.reportError=Raportați eroarea

#Search
word.search=Căutare

#Searching...
word.searching=Căutând...

#Send
word.send=Trimiteți

#Waiting...
word.waiting___=Așteptând...