#Current verse
msg.currentVerse=Текущий стих

#Could not connect to server
msg.errorConnect=Не удалось подключиться к серверу

#Error - Empty text
msg.errorContIsEmpty=Ошибка - Пустой текст

#Error - Very large text
msg.errorContVeryLarge=Ошибка - Очень большой текст

#Invalid File: {0}
msg.errorInvalidFile=Недопустимый файл: {0}

#Error - Try again
msg.errorTryAgain=Ошибка! Попробуйте снова.

#Exact phrase
msg.exactFrase=Точная фраза

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Сообщение отправлено!\nМы рассмотрим ваше предложение.\nСпасибо....

#Results: {0}
msg.results_x=Результаты: {0}

#Sort by
msg.sortBy=Сортировать по

#Suggested edition
msg.suggestedEdition=Предлагаемая редакция

#Double-click to select
msg.toolTipTextJListResult=Дважды щелкните, чтобы выбрать

#Type your search here...
msg.toolTipTextJText=Введите поисковый запрос здесь...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Слово целиком

#List: 
VerseSearchPanel.jLabelList.text=Список: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Вся Библия

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Все слова

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Любое слово

#Book:
VerseSearchPanel.jRadioButtonBook.text=Книга:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Новый Завет

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Ветхий Завет

#Cancel
word.cancel=Отменить

#Error
word.error=Ошибка

#Help
word.help=Помощь

#Home
word.home=Главная

#Natural
word.natural=По порядку

#Relevance
word.relevance=По совпадению

#Report Error
word.reportError=Сообщить об ошибке

#Search
word.search=Поиск

#Searching...
word.searching=Идет поиск...

#Send
word.send=Отправить

#Waiting...
word.waiting___=Ожидание...