#Current verse
msg.currentVerse=Trenutni stih

#Could not connect to server
msg.errorConnect=Није могуће повезивање са сервером

#Error - Empty text
msg.errorContIsEmpty=Грешка - Празан текст

#Error - Very large text
msg.errorContVeryLarge=Грешка - Текст превелик

#Invalid File: {0}
msg.errorInvalidFile=Pogrešna Veličina: {0}

#Error - Try again
msg.errorTryAgain=Грешка - Покушајте поново

#Exact phrase
msg.exactFrase=Тачан израз

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Порука послата!\nАнализираћемо ваш предлог.\nХвала.

#Results: {0}
msg.results_x=Резултати: {0}

#Sort by
msg.sortBy=Сортирај по

#Suggested edition
msg.suggestedEdition=Предложена измена

#Double-click to select
msg.toolTipTextJListResult=Двоструки клик за избор

#Type your search here...
msg.toolTipTextJText=Унесите вашу претрагу овде...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Цела реч

#List: 
VerseSearchPanel.jLabelList.text=Lista: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Цела Библија

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Све речи

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Било која реч

#Book:
VerseSearchPanel.jRadioButtonBook.text=Књига:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Нови завет

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Стари завет

#Cancel
word.cancel=Poništiti

#Error
word.error=Greška

#Help
word.help=Pomoć

#Home
word.home=Kući

#Natural
word.natural=Природно

#Relevance
word.relevance=Релевантност

#Report Error
word.reportError=Izveštaj o grešci

#Search
word.search=Pretraga

#Searching...
word.searching=Тражим...

#Send
word.send=Poslati

#Waiting...
word.waiting___=Čekanje...