#Current verse
msg.currentVerse=தற்போதைய வசனம்

#Could not connect to server
msg.errorConnect=சேவையகத்துடன் இணைக்க முடியவில்லை

#Error - Empty text
msg.errorContIsEmpty=பிழை - உரை காலியாக உள்ளது

#Error - Very large text
msg.errorContVeryLarge=பிழை - உரை மிகவும் பெரியது

#Invalid File: {0}
msg.errorInvalidFile=தவறான கோப்பு: {0}

#Error - Try again
msg.errorTryAgain=பிழை - மீண்டும் முயற்சிக்கவும்

#Exact phrase
msg.exactFrase=சரியான வாக்கியம்

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=செய்தி அனுப்பப்பட்டது!\nநாங்கள் உங்கள் பரிந்துரையை ஆய்வு செய்வோம்.\nநன்றி.

#Results: {0}
msg.results_x=முடிவுகள்: {0}

#Sort by
msg.sortBy=வரிசைப்படுத்தவும்

#Suggested edition
msg.suggestedEdition=சூத்திரம் பரிந்துரை

#Double-click to select
msg.toolTipTextJListResult=தேர்வு செய்ய இரட்டை கிளிக் செய்யவும்

#Type your search here...
msg.toolTipTextJText=உங்கள் தேடலை இங்கே உள்ளிடவும்...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=முழு சொல்

#List: 
VerseSearchPanel.jLabelList.text=பட்டியல்: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=முழு பைபிள்

#All words
VerseSearchPanel.jRadioButtonAllWords.text=எல்லா சொற்களும்

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=எந்த சொல்

#Book:
VerseSearchPanel.jRadioButtonBook.text=புத்தகம்:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=புதிய ஏற்பாடு

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=பழைய ஏற்பாடு

#Cancel
word.cancel=ரத்து செய்யவும்

#Error
word.error=பிழை

#Help
word.help=உதவி

#Home
word.home=தொடக்கம்

#Natural
word.natural=இயற்கை

#Relevance
word.relevance=முக்கியத்துவம்

#Report Error
word.reportError=பிழையைப் புகாரளிக்கவும்

#Search
word.search=தேடல்

#Searching...
word.searching=தேடுகிறது...

#Send
word.send=அனுப்பவும்

#Waiting...
word.waiting___=காத்திருக்கிறது...