#Current verse
msg.currentVerse=ప్రస్తుత వచనం

#Could not connect to server
msg.errorConnect=సర్వర్‌కు కనెక్ట్ కావడం సాధ్యం కాలేదు

#Error - Empty text
msg.errorContIsEmpty=లోపం - ఖాళీ పాఠ్యం

#Error - Very large text
msg.errorContVeryLarge=లోపం - చాలా పెద్ద పాఠ్యం

#Invalid File: {0}
msg.errorInvalidFile=చెల్లని ఫైల్: {0}

#Error - Try again
msg.errorTryAgain=లోపం - మళ్లీ ప్రయత్నించండి

#Exact phrase
msg.exactFrase=ఖచ్చితమైన వాక్యం

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=సందేశం పంపబడింది!\nమీ సిఫారసును మేము పరిశీలిస్తాము.\nధన్యవాదాలు.

#Results: {0}
msg.results_x=ఫలితాలు: {0}

#Sort by
msg.sortBy=క్రమబద్ధీకరించు

#Suggested edition
msg.suggestedEdition=సిఫారసు చేసిన సవరణ

#Double-click to select
msg.toolTipTextJListResult=ఎంచుకోవడానికి డబుల్ క్లిక్ చేయండి

#Type your search here...
msg.toolTipTextJText=మీ శోధన ఇక్కడ టైప్ చేయండి...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=పూర్తి పదం

#List: 
VerseSearchPanel.jLabelList.text=జాబితా: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=మొత్తం బైబిల్

#All words
VerseSearchPanel.jRadioButtonAllWords.text=అన్ని పదాలు

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=ఏదైనా పదం

#Book:
VerseSearchPanel.jRadioButtonBook.text=పుస్తకం:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=కొత్త ఒడంబడిక

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=పాత ఒడంబడిక

#Cancel
word.cancel=రద్దు చేయండి

#Error
word.error=లోపం

#Help
word.help=సహాయం

#Home
word.home=ప్రారంభం

#Natural
word.natural=స్వాభావికమైన

#Relevance
word.relevance=సంబంధితత

#Report Error
word.reportError=లోపాన్ని నివేదించండి

#Search
word.search=శోధన

#Searching...
word.searching=శోధిస్తున్నాను...

#Send
word.send=అనుమతించు

#Waiting...
word.waiting___=కాకుండా...