#Current verse
msg.currentVerse=ข้อพระคัมภีร์ปัจจุบัน

#Could not connect to server
msg.errorConnect=ไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์ได้

#Error - Empty text
msg.errorContIsEmpty=ข้อผิดพลาด - ข้อความว่าง

#Error - Very large text
msg.errorContVeryLarge=ข้อผิดพลาด - ข้อความใหญ่เกินไป

#Invalid File: {0}
msg.errorInvalidFile=ไฟล์ไม่ถูกต้อง: {0}

#Error - Try again
msg.errorTryAgain=ข้อผิดพลาด - กรุณาลองอีกครั้ง

#Exact phrase
msg.exactFrase=ประโยคที่แน่นอน

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=ข้อความถูกส่งแล้ว!\nเราจะตรวจสอบข้อเสนอของคุณ.\nขอบคุณ.

#Results: {0}
msg.results_x=ผลลัพธ์: {0}

#Sort by
msg.sortBy=เรียงตาม

#Suggested edition
msg.suggestedEdition=การแก้ไขที่แนะนำ

#Double-click to select
msg.toolTipTextJListResult=คลิกสองครั้งเพื่อเลือก

#Type your search here...
msg.toolTipTextJText=กรุณาใส่การค้นหาของคุณที่นี่...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=คำทั้งหมด

#List: 
VerseSearchPanel.jLabelList.text=รายการ: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=พระคัมภีร์ทั้งหมด

#All words
VerseSearchPanel.jRadioButtonAllWords.text=ทุกคำ

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=คำใดก็ได้

#Book:
VerseSearchPanel.jRadioButtonBook.text=หนังสือ:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=พันธสัญญาใหม่

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=พันธสัญญาเดิม

#Cancel
word.cancel=ยกเลิก

#Error
word.error=ข้อผิดพลาด

#Help
word.help=ช่วยเหลือ

#Home
word.home=เริ่มต้น

#Natural
word.natural=ธรรมชาติ

#Relevance
word.relevance=ความเกี่ยวข้อง

#Report Error
word.reportError=รายงานข้อผิดพลาด

#Search
word.search=การค้นหา

#Searching...
word.searching=กำลังค้นหา...

#Send
word.send=ส่ง

#Waiting...
word.waiting___=รออยู่...