#Current verse
msg.currentVerse=Kasalukuyang taludtod

#Could not connect to server
msg.errorConnect=Hindi makakonekta sa server

#Error - Empty text
msg.errorContIsEmpty=Error - Walang laman na teksto

#Error - Very large text
msg.errorContVeryLarge=Error - Napakalaking teksto

#Invalid File: {0}
msg.errorInvalidFile=Hindi wastong file: {0}

#Error - Try again
msg.errorTryAgain=Error - Subukan muli

#Exact phrase
msg.exactFrase=Eksaktong parirala

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Mensaheng naipadala!\nSusuriin namin ang iyong mungkahi.\nSalamat.

#Results: {0}
msg.results_x=Mga Resulta: {0}

#Sort by
msg.sortBy=Ayusin ayon sa

#Suggested edition
msg.suggestedEdition=Inirekomendang pagbabago

#Double-click to select
msg.toolTipTextJListResult=Double click upang pumili

#Type your search here...
msg.toolTipTextJText=I-type ang iyong paghahanap dito...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Buong Salita

#List: 
VerseSearchPanel.jLabelList.text=Ilista: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Buong Bibliya

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Lahat ng salita

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Anumang salita

#Book:
VerseSearchPanel.jRadioButtonBook.text=Aklat:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Bagong Tipan

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Lumang Tipan

#Cancel
word.cancel=Kanselahin

#Error
word.error=Error

#Help
word.help=Tulong

#Home
word.home=Simula

#Natural
word.natural=Natural

#Relevance
word.relevance=Kahalagahan

#Report Error
word.reportError=Iulat ang Error

#Search
word.search=Paghahanap

#Searching...
word.searching=Naghahanap...

#Send
word.send=Ipadala

#Waiting...
word.waiting___=Naghihintay...