#Current verse
msg.currentVerse=Mevcut ayet

#Could not connect to server
msg.errorConnect=Sunucuya bağlanılamadı

#Error - Empty text
msg.errorContIsEmpty=Hata - Boş metin

#Error - Very large text
msg.errorContVeryLarge=Hata - Metin çok büyük

#Invalid File: {0}
msg.errorInvalidFile=Geçersiz Dosya: {0}

#Error - Try again
msg.errorTryAgain=Hata - Lütfen tekrar deneyin

#Exact phrase
msg.exactFrase=Tam cümle

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Mesaj gönderildi!\nÖnerinizi inceleyeceğiz.\nTeşekkür ederiz.

#Results: {0}
msg.results_x=Sonuçlar: {0}

#Sort by
msg.sortBy=Sırala

#Suggested edition
msg.suggestedEdition=Önerilen düzenleme

#Double-click to select
msg.toolTipTextJListResult=Seçmek için çift tıklayın

#Type your search here...
msg.toolTipTextJText=Araştırmanızı buraya yazın...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Tam Kelime

#List: 
VerseSearchPanel.jLabelList.text=Listele: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Tüm Kutsal Kitap

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Tüm kelimeler

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Herhangi bir kelime

#Book:
VerseSearchPanel.jRadioButtonBook.text=Kitap:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Yeni Ahit

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Eski Ahit

#Cancel
word.cancel=İptal

#Error
word.error=Hata

#Help
word.help=Yardım

#Home
word.home=Başlangıç

#Natural
word.natural=Doğal

#Relevance
word.relevance=Alaka

#Report Error
word.reportError=Hata Bildir

#Search
word.search=Araştırma

#Searching...
word.searching=Aranıyor...

#Send
word.send=Gönder

#Waiting...
word.waiting___=Bekleniyor...