#Current verse
msg.currentVerse=Поточний вірш

#Could not connect to server
msg.errorConnect=Не вдалося підключитися до сервера

#Error - Empty text
msg.errorContIsEmpty=Помилка - Текст відсутній

#Error - Very large text
msg.errorContVeryLarge=Помилка - Текст занадто великий

#Invalid File: {0}
msg.errorInvalidFile=Недопустимий файл: {0}

#Error - Try again
msg.errorTryAgain=Помилка - Спробуйте знову

#Exact phrase
msg.exactFrase=Точна фраза

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Повідомлення відправлено!\nМи розглянемо вашу пропозицію.\nДякуємо...

#Results: {0}
msg.results_x=Результати: {0}

#Sort by
msg.sortBy=Сортувати за

#Suggested edition
msg.suggestedEdition=Запропоноване редагування

#Double-click to select
msg.toolTipTextJListResult=Двічі натисніть, щоб вибрати

#Type your search here...
msg.toolTipTextJText=Введіть ваш пошуковий запит тут...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Ціле слово

#List: 
VerseSearchPanel.jLabelList.text=Список: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Вся Біблія

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Всі слова

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Будь-яке слово

#Book:
VerseSearchPanel.jRadioButtonBook.text=Книга:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Новий Заповіт

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Старий Заповіт

#Cancel
word.cancel=Скасувати

#Error
word.error=Помилка

#Help
word.help=Допомога

#Home
word.home=Головна

#Natural
word.natural=Природний

#Relevance
word.relevance=Актуальний

#Report Error
word.reportError=Повідомити про помилку

#Search
word.search=Пошук

#Searching...
word.searching=Шукаємо...

#Send
word.send=Надіслати

#Waiting...
word.waiting___=Очікування...