#Current verse
msg.currentVerse=موجودہ آیت

#Could not connect to server
msg.errorConnect=سرور سے جڑنے میں ناکام

#Error - Empty text
msg.errorContIsEmpty=غلطی - خالی متن

#Error - Very large text
msg.errorContVeryLarge=غلطی - متن بہت بڑا ہے

#Invalid File: {0}
msg.errorInvalidFile=غلط فائل: {0}

#Error - Try again
msg.errorTryAgain=غلطی - دوبارہ کوشش کریں

#Exact phrase
msg.exactFrase=بالکل وہی جملہ

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=پیغام بھیجا گیا!\nہم آپ کی تجویز کا جائزہ لیں گے۔\nشکریہ.

#Results: {0}
msg.results_x=نتائج: {0}

#Sort by
msg.sortBy=ترتیب دیں

#Suggested edition
msg.suggestedEdition=تجویز کردہ ترمیم

#Double-click to select
msg.toolTipTextJListResult=منتخب کرنے کے لیے دو بار کلک کریں

#Type your search here...
msg.toolTipTextJText=یہاں اپنی تلاش درج کریں...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=مکمل لفظ

#List: 
VerseSearchPanel.jLabelList.text=فہرست: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=پورا بائبل

#All words
VerseSearchPanel.jRadioButtonAllWords.text=تمام الفاظ

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=کسی بھی لفظ

#Book:
VerseSearchPanel.jRadioButtonBook.text=کتاب:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=نیا عہد نامہ

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=قدیم عہد نامہ

#Cancel
word.cancel=منسوخ کریں

#Error
word.error=غلطی

#Help
word.help=مدد

#Home
word.home=شروع

#Natural
word.natural=قدرتی

#Relevance
word.relevance=اہمیت

#Report Error
word.reportError=غلطی کی رپورٹ کریں

#Search
word.search=تلاش

#Searching...
word.searching=تلاش کر رہے ہیں...

#Send
word.send=بھیجیں

#Waiting...
word.waiting___=انتظار کر رہے ہیں...