#Current verse
msg.currentVerse=Câu hiện tại

#Could not connect to server
msg.errorConnect=Không thể kết nối với máy chủ

#Error - Empty text
msg.errorContIsEmpty=Lỗi - Văn bản trống

#Error - Very large text
msg.errorContVeryLarge=Lỗi - Văn bản quá lớn

#Invalid File: {0}
msg.errorInvalidFile=Tệp không hợp lệ: {0}

#Error - Try again
msg.errorTryAgain=Lỗi - Vui lòng thử lại

#Exact phrase
msg.exactFrase=Câu chính xác

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Tin nhắn đã được gửi!\nChúng tôi sẽ xem xét đề xuất của bạn.\nCảm ơn.

#Results: {0}
msg.results_x=Kết quả: {0}

#Sort by
msg.sortBy=Sắp xếp theo

#Suggested edition
msg.suggestedEdition=Chỉnh sửa được đề xuất

#Double-click to select
msg.toolTipTextJListResult=Nhấp đúp để chọn

#Type your search here...
msg.toolTipTextJText=Nhập tìm kiếm của bạn ở đây...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Từ đầy đủ

#List: 
VerseSearchPanel.jLabelList.text=Danh sách: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Toàn bộ Kinh Thánh

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Tất cả các từ

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Bất kỳ từ nào

#Book:
VerseSearchPanel.jRadioButtonBook.text=Sách:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Tân Ước

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Cựu Ước

#Cancel
word.cancel=Hủy bỏ

#Error
word.error=Lỗi

#Help
word.help=Trợ giúp

#Home
word.home=Trang chủ

#Natural
word.natural=Tự nhiên

#Relevance
word.relevance=Sự liên quan

#Report Error
word.reportError=Báo cáo lỗi

#Search
word.search=Tìm kiếm

#Searching...
word.searching=Đang tìm kiếm...

#Send
word.send=Gửi đi

#Waiting...
word.waiting___=Đang chờ...