#Current verse
msg.currentVerse=Iwe-ẹkọ lọwọlọwọ

#Could not connect to server
msg.errorConnect=Ko le sopọ si olupin

#Error - Empty text
msg.errorContIsEmpty=Aṣiṣe - Ọrọ ofo

#Error - Very large text
msg.errorContVeryLarge=Aṣiṣe - Ọrọ ti o tobi ju

#Invalid File: {0}
msg.errorInvalidFile=Faili Aisi: {0}

#Error - Try again
msg.errorTryAgain=Aṣiṣe - Jọwọ tun gbiyanju

#Exact phrase
msg.exactFrase=Gbolohun gangan

#Message sent!\nWe will consider your suggestion.\nThank you....
msg.reportSuccess=Ifiranṣẹ ti a firanṣẹ!\nA yoo ṣe ayẹwo imọran rẹ.\nO ṣeun.

#Results: {0}
msg.results_x=Esi: {0}

#Sort by
msg.sortBy=Ṣeto nipasẹ

#Suggested edition
msg.suggestedEdition=Atilẹyin ti a dabaa

#Double-click to select
msg.toolTipTextJListResult=Tẹ lẹmeji lati yan

#Type your search here...
msg.toolTipTextJText=Tẹ ọrọ iwadi rẹ nibi...

#Whole word
VerseSearchPanel.jCheckBoxWholeWord.text=Ọrọ Gbogbo

#List: 
VerseSearchPanel.jLabelList.text=Atokọ: 

#All Bible
VerseSearchPanel.jRadioButtonAllBible.text=Gbogbo Bibeli

#All words
VerseSearchPanel.jRadioButtonAllWords.text=Gbogbo awọn ọrọ

#Any word
VerseSearchPanel.jRadioButtonAnyWord.text=Ohun gbogbo

#Book:
VerseSearchPanel.jRadioButtonBook.text=Iwe:

#New Testament
VerseSearchPanel.jRadioButtonNewTestament.text=Iwe Tuntun

#Old Testament
VerseSearchPanel.jRadioButtonOldTestament.text=Iwe Atijọ

#Cancel
word.cancel=Fagilee

#Error
word.error=Aṣiṣe

#Help
word.help=Iranlọwọ

#Home
word.home=Ibẹrẹ

#Natural
word.natural=Ibi-nla

#Relevance
word.relevance=Iṣeduro

#Report Error
word.reportError=Jẹ́wọ́ Aṣiṣe

#Search
word.search=Iwadii

#Searching...
word.searching=N wa...

#Send
word.send=Firanṣẹ

#Waiting...
word.waiting___=N duro de...