#You can add and/or remove words directly in the file
M_001=Sözləri birbaşa faylda əlavə edə və ya silə bilərsiniz

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Sözlər <b>sətir sonu</b> ilə ayrılmalıdır, yəni <b>bir söz bir sətirdə</b>

#Open dictionary of words
M_003=Söz lüğətini aç

#Spell Check
M_004=Yazı Düzəldici

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>Yazı Düzəldici</b> səhv sözləri və cümlənin başlanğıcında kiçik hərflə başlayan sözləri yoxlayır

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=O <b>dəyişiklik</b>, çoxluq, cins və s. düzəltmir, yalnız <b>yazılış</b>ı düzəldir

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Lüğətə söz əlavə edərkən diqqətli olun, çünki bu sözün bütün yeni halları proqramın digər yerlərində düzgün hesab ediləcək

#When you add a word to the dictionary, only the original word will be added
M_008=Lüğətə bir söz əlavə edərkən yalnız orijinal forma əlavə ediləcək

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>Varyasiyalar</i> hələ də lüğətə əlavə olunana qədər səhv hesab ediləcək

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Söz <b>LimaGiran</b> lüğətə əlavə edildi

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=<b>limagiran</b> kimi halları hələ də səhv hesab ediləcək

#Add to dictionary
M_ADD_TO_DICTIONARY=Lüğətə əlavə et

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Hər hansı bir sözün böyük hərflə başlamasına icazə verin

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Sətir sonundan sonra kiçik hərflə başlayan sözü yoxlayın

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Noktalama işarəsindən sonra kiçik hərflə başlayan sözü yoxlayın

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Düzəldicini deaktiv et

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Düzəldicini aktivləşdir

#Ignore all
M_IGNORE_ALL=Hər şeyi göz ardı et

#No Suggestions
M_NO_SUGGESTIONS=Təklif yoxdur

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Düzəldici parametrləri

#Example
W_001=Nümunə

#Copy
W_COPY=Kopyala

#Cut
W_CUT=Kəsmək

#Dictionary
W_DICTIONARY=Lüğət

#Enable
W_ENABLE=Aktivləşdir

#Ignore
W_IGNORE=Göz ardı et

#Paste
W_PASTE=Yapışdır

#Redo
W_REDO=Yenidən düzəlt

#Undo
W_UNDO=Geri al