#You can add and/or remove words directly in the file
M_001=আপনি সরাসরি ফাইলে শব্দ যোগ বা মুছতে পারেন

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=শব্দগুলি <b>লাইন ব্রেক</b> দ্বারা আলাদা করা উচিত, অর্থাৎ, <b>প্রতি লাইনে একটি শব্দ</b>

#Open dictionary of words
M_003=শব্দের অভিধান খুলুন

#Spell Check
M_004=বানান পরীক্ষক

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>বানান পরীক্ষক</b> ভুল শব্দ এবং ছোট হাতের অক্ষরে বাক্যের শুরুতে শব্দ পরীক্ষা করে

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=তিনি <b>সংশোধন</b> করেন না সম্মতি, বহুবচন, লিঙ্গ, ইত্যাদি শুধুমাত্র <b>বানান</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=অভিধানে শব্দ যোগ করার সময় সতর্ক থাকুন, কারণ এই শব্দের সমস্ত নতুন ঘটনার জন্য প্রোগ্রামের অন্য কোথাও সঠিক হিসাবে বিবেচিত হবে

#When you add a word to the dictionary, only the original word will be added
M_008=অভিধানে একটি শব্দ যোগ করার সময়, শুধুমাত্র মূল রূপ যোগ করা হবে

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>ভিন্নতা</i>গুলি ভুল হিসাবে বিবেচিত হতে থাকবে যতক্ষণ না সেগুলি অভিধানে যোগ করা হয়

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=শব্দ <b>LimaGiran</b> অভিধানে যোগ করা হয়েছে

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=ঘটনাগুলি যেমন <b>limagiran</b> ভুল হিসাবে বিবেচিত হতে থাকবে

#Add to dictionary
M_ADD_TO_DICTIONARY=অভিধানে যোগ করুন

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=যেকোনো শব্দের প্রথম অক্ষর বড় হাতের অক্ষর হতে পারে

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=লাইন ব্রেকের পরে ছোট হাতের অক্ষরে শব্দ পরীক্ষা করুন

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=পুনঃচিহ্নের পরে ছোট হাতের অক্ষরে শব্দ পরীক্ষা করুন

#Disable Spell Check
M_DISABLE_SPELL_CHECK=বানান পরীক্ষক নিষ্ক্রিয় করুন

#Enable Spell Check
M_ENABLE_SPELL_CHECK=বানান পরীক্ষক সক্রিয় করুন

#Ignore all
M_IGNORE_ALL=সবকিছু উপেক্ষা করুন

#No Suggestions
M_NO_SUGGESTIONS=কোনো পরামর্শ নেই

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=বানান পরীক্ষকের সেটিংস

#Example
W_001=উদাহরণ

#Copy
W_COPY=কপি করুন

#Cut
W_CUT=কাটুন

#Dictionary
W_DICTIONARY=অভিধান

#Enable
W_ENABLE=সক্রিয় করুন

#Ignore
W_IGNORE=উপেক্ষা করুন

#Paste
W_PASTE=পেস্ট করুন

#Redo
W_REDO=পুনরায় করুন

#Undo
W_UNDO=পুনরুদ্ধার করুন