#You can add and/or remove words directly in the file
M_001=Sie können Wörter direkt in der Datei hinzufügen und/oder entfernen

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Die Wörter müssen durch <b>Zeilenumbruch</b> getrennt werden, das heißt, <b>ein Wort pro Zeile</b>

#Open dictionary of words
M_003=Wörterbuch öffnen

#Spell Check
M_004=Rechtschreibprüfung

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=Die <b>Rechtschreibprüfung</b> überprüft inkorrekte Wörter und Wörter, die mit einem Kleinbuchstaben am Satzanfang beginnen

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Es <b>korrigiert</b> keine Übereinstimmung, Plural, Geschlecht usw., sondern nur <b>Rechtschreibung</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Achten Sie darauf, Wörter zum Wörterbuch hinzuzufügen, da alle neuen Vorkommen dieses Wortes an anderer Stelle im Programm als korrekt angesehen werden

#When you add a word to the dictionary, only the original word will be added
M_008=Beim Hinzufügen eines Wortes zum Wörterbuch wird nur die ursprüngliche Form hinzugefügt

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=Die <i>Variationen</i> werden weiterhin als inkorrekt angesehen, bis sie ebenfalls zum Wörterbuch hinzugefügt werden

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Das Wort <b>LimaGiran</b> wurde zum Wörterbuch hinzugefügt

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Vorkommen wie <b>limagiran</b> werden weiterhin als inkorrekt angesehen

#Add to dictionary
M_ADD_TO_DICTIONARY=Zum Wörterbuch hinzufügen

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Erlauben, dass jedes Wort mit einem Großbuchstaben beginnt

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Überprüfen Sie das Wort mit einem Kleinbuchstaben nach dem Zeilenumbruch

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Überprüfen Sie das Wort mit einem Kleinbuchstaben nach der Interpunktion

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Rechtschreibprüfung deaktivieren

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Rechtschreibprüfung aktivieren

#Ignore all
M_IGNORE_ALL=Alles ignorieren

#No Suggestions
M_NO_SUGGESTIONS=Keine Vorschläge

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Einstellungen der Rechtschreibprüfung

#Example
W_001=Beispiel

#Copy
W_COPY=Kopieren

#Cut
W_CUT=Ausschneiden

#Dictionary
W_DICTIONARY=Wörterbuch

#Enable
W_ENABLE=Aktivieren

#Ignore
W_IGNORE=Ignorieren

#Paste
W_PASTE=Einfügen

#Redo
W_REDO=Wiederholen

#Undo
W_UNDO=Rückgängig machen