#You can add and/or remove words directly in the file
M_001=Puede agregar y/o quitar palabras directamente en el archivo

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Las palabras se deben separar por <b>salto de línea</b>, o sea, <b>una palabra por línea<b/>

#Open dictionary of words
M_003=Abrir diccionario de palabras

#Spell Check
M_004=Corrector Ortográfico

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=El <b>Corrector Ortográfico</b> comprueba las palabras incorrectas y las palabras con el principio de la frase con la letra minúscula

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Él <b>no</b> corrige concordancia, plural, género, etc. sólo <b>ortografía</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Tenga cuidado al agregar palabras al diccionario, ya que todas las nuevas apariciones de esta palabra se considerarán correctas en otras partes del programa

#When you add a word to the dictionary, only the original word will be added
M_008=Al agregar una palabra al diccionario, sólo se agregará la palabra original

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=Las <i>variaciones</i> seguirán siendo consideradas incorrectas hasta que también se agreguen al diccionario

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=La palabra <b>LimaGiran</b> fue agregada al diccionario

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Las apariciones como <b>limagiran</b> seguirán siendo consideradas incorrectas

#Add to dictionary
M_ADD_TO_DICTIONARY=Añadir al diccionario

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Permitir que cualquier palabra comience con letra mayúscula

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Verificar palabra con letra minúscula después de salto de línea

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Verificar palabra con letra minúscula después de la puntuación

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Desactivar Corrector

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Activar Corrector

#Ignore all
M_IGNORE_ALL=Ignorar todo

#No Suggestions
M_NO_SUGGESTIONS=Sin sugerencias

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Configuraciones del corrector

#Example
W_001=Ejemplo

#Copy
W_COPY=Copiar

#Cut
W_CUT=Cortar

#Dictionary
W_DICTIONARY=Diccionario

#Enable
W_ENABLE=Activar

#Ignore
W_IGNORE=Ignorar

#Paste
W_PASTE=Pegar

#Redo
W_REDO=Rehacer

#Undo
W_UNDO=Deshacer