#You can add and/or remove words directly in the file
M_001=Vous pouvez ajouter et/ou supprimer des mots directement dans le fichier

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Les mots doivent être séparés par un <b>saut de ligne</b>, c'est-à-dire <b>un mot par ligne<b/>

#Open dictionary of words
M_003=Ouvrir le dictionnaire de mots

#Spell Check
M_004=Correcteur d'orthographe

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=Le <b>correcteur d'orthographe</b> vérifie les mots mal orthographiés et les mots en minuscules

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Il <b>non</b> corrige l'accord, le pluriel, le genre, etc. juste <b>l'orthographe</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Soyez prudent lorsque vous ajoutez des mots au dictionnaire, car toutes les nouvelles occurrences de ce mot seront considérées comme correctes n'importe où ailleurs dans le programme

#When you add a word to the dictionary, only the original word will be added
M_008=Lorsque vous ajoutez un mot au dictionnaire, seul le mot d'origine sera ajouté

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=Les <i>variations</i> continueront d'être considérées comme incorrectes jusqu'à ce qu'elles soient également ajoutées au dictionnaire

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Le mot <b>LimaGiran</b> a été ajouté au dictionnaire

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Des occurrences comme <b>limagiran</b> continueront d'être considérées comme incorrectes

#Add to dictionary
M_ADD_TO_DICTIONARY=Ajouter au dictionnaire

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Permettez à n'importe quel mot de commencer par une majuscule

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Vérifier le mot en minuscule après le saut de ligne

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Vérifier le mot en minuscule après la ponctuation

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Désactiver le correcteur d'orthographe

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Activer le correcteur d'orthographe

#Ignore all
M_IGNORE_ALL=Ignorer tout

#No Suggestions
M_NO_SUGGESTIONS=Pas de suggestions

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Paramètres du correcteur d'orthographe

#Example
W_001=Exemple

#Copy
W_COPY=Copier

#Cut
W_CUT=Couper

#Dictionary
W_DICTIONARY=Dictionnaire

#Enable
W_ENABLE=Activer

#Ignore
W_IGNORE=Ignorer

#Paste
W_PASTE=Coller

#Redo
W_REDO=Refaire

#Undo
W_UNDO=Annuler