#You can add and/or remove words directly in the file
M_001=आप सीधे फ़ाइल में शब्द जोड़ या हटा सकते हैं

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=शब्दों को <b>लाइन ब्रेक</b> द्वारा अलग किया जाना चाहिए, अर्थात्, <b>प्रति पंक्ति एक शब्द</b>

#Open dictionary of words
M_003=शब्दों का शब्दकोश खोलें

#Spell Check
M_004=वर्तनी जांचक

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>वर्तनी जांचक</b> गलत शब्दों और वाक्य के शुरू में छोटे अक्षर से शुरू होने वाले शब्दों की जांच करता है

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=यह <b>संयोग</b>, बहुवचन, लिंग आदि को ठीक नहीं करता है, केवल <b>वर्तनी</b> को ही ठीक करता है

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=शब्दकोश में शब्द जोड़ते समय ध्यान दें, क्योंकि इस शब्द की सभी नई घटनाएँ कार्यक्रम के किसी अन्य स्थान पर सही मानी जाएंगी

#When you add a word to the dictionary, only the original word will be added
M_008=शब्दकोश में एक शब्द जोड़ते समय, केवल मूल रूप जोड़ा जाएगा

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>विविधताएँ</i> तब तक गलत मानी जाएंगी जब तक कि उन्हें भी शब्दकोश में नहीं जोड़ा जाता

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=शब्द <b>LimaGiran</b> शब्दकोश में जोड़ा गया है

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=जैसे <b>limagiran</b> की घटनाएँ गलत मानी जाएंगी

#Add to dictionary
M_ADD_TO_DICTIONARY=शब्दकोश में जोड़ें

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=किसी भी शब्द को बड़े अक्षर से शुरू करने की अनुमति दें

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=लाइन ब्रेक के बाद छोटे अक्षर से शब्द की जांच करें

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=विराम चिह्न के बाद छोटे अक्षर से शब्द की जांच करें

#Disable Spell Check
M_DISABLE_SPELL_CHECK=जांचक को निष्क्रिय करें

#Enable Spell Check
M_ENABLE_SPELL_CHECK=जांचक को सक्रिय करें

#Ignore all
M_IGNORE_ALL=सब कुछ अनदेखा करें

#No Suggestions
M_NO_SUGGESTIONS=कोई सुझाव नहीं

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=जांचक की सेटिंग्स

#Example
W_001=उदाहरण

#Copy
W_COPY=कॉपी करें

#Cut
W_CUT=कट करें

#Dictionary
W_DICTIONARY=शब्दकोश

#Enable
W_ENABLE=सक्रिय करें

#Ignore
W_IGNORE=अनदेखा करें

#Paste
W_PASTE=चिपकाएँ

#Redo
W_REDO=फिर से करें

#Undo
W_UNDO=पूर्ववत करें