#You can add and/or remove words directly in the file
M_001=Szavakat közvetlenül a fájlban adhat hozzá és/vagy távolíthat el

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=A szavakat <b>új sorral</b> kell elválasztani, vagyis <b>egy szó egy sor<b/>

#Open dictionary of words
M_003=Szavak szótárának megnyitása

#Spell Check
M_004=Helyesírás-ellenőrző

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=A <b>Helyesírás-ellenőrző</b> ellenőrzi a helytelen szavakat és a mondat elején kisbetűvel kezdődő szavakat

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Ez <b>nem</b> javítja a ragozást, többes számot, nemet stb., csak <b>helyesírást</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Figyeljen a szavak szótárba való hozzáadásakor, mivel az új előfordulások ezen szóból minden más helyen a programban helyesnek lesznek tekintve

#When you add a word to the dictionary, only the original word will be added
M_008=Amikor egy szót hozzáad a szótárhoz, csak az eredeti forma kerül hozzáadásra

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=A <i>változatok</i> továbbra is helytelennek számítanak, amíg azok is hozzá nem kerülnek a szótárhoz

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=A <b>LimaGiran</b> szó hozzá lett adva a szótárhoz

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Az olyan előfordulások, mint a <b>limagiran</b>, továbbra is helytelennek számítanak

#Add to dictionary
M_ADD_TO_DICTIONARY=Hozzáadás a szótárhoz

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Engedélyezze, hogy bármely szó nagybetűvel kezdődjön

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Ellenőrizze a kisbetűs szót az új sor után

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Ellenőrizze a kisbetűs szót a pontozás után

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Helyesírás-ellenőrző letiltása

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Helyesírás-ellenőrző aktiválása

#Ignore all
M_IGNORE_ALL=Mindent figyelmen kívül hagyni

#No Suggestions
M_NO_SUGGESTIONS=Nincs javaslat

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Helyesírás-ellenőrző beállításai

#Example
W_001=Példa

#Copy
W_COPY=Másolás

#Cut
W_CUT=Kivágás

#Dictionary
W_DICTIONARY=Szótár

#Enable
W_ENABLE=Aktiválás

#Ignore
W_IGNORE=Figyelmen kívül hagyás

#Paste
W_PASTE=Beillesztés

#Redo
W_REDO=Újra

#Undo
W_UNDO=Visszavonás