#You can add and/or remove words directly in the file
M_001=Puoi aggiungere e/o rimuovere parole direttamente nel file

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Le parole devono essere separate da <b>interruzione di riga</b>, ovvero <b>una parola per riga<b/>

#Open dictionary of words
M_003=Aprire dizionario di parole

#Spell Check
M_004=Correttore Ortografico

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=Il <b>Correttore Ortografico</b> verifica parole errate e parole con inizio di frase con lettera minuscola

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Esso <b>non</b> corregge la concordanza, il plurale, il genere, solo l'<b>ortografia</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Prestare attenzione quando si aggiungono parole al dizionario, poiché tutte le nuove occorrenze di questa parola saranno considerate corrette in qualsiasi altra parte del programma

#When you add a word to the dictionary, only the original word will be added
M_008=Aggiungendo una parola al dizionario, verrà aggiunta solo la forma originale

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=Le <i>variazioni</i> continueranno ad essere considerate errate fino a quando non saranno anche aggiunte al dizionario

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=La parola <b>LimaGiran</b> è stata aggiunta al dizionario

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Occorrenze come <b>limagiran</b> continueranno ad essere considerate errate

#Add to dictionary
M_ADD_TO_DICTIONARY=Aggiungere al dizionario

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Consentire che qualsiasi parola inizi con una lettera maiuscola

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Verificare parola con lettera minuscola dopo interruzione di riga

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Verificare la parola con lettera minuscola dopo la punteggiatura

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Disattivare Correttore

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Attivare Correttore

#Ignore all
M_IGNORE_ALL=Ignorare tutto

#No Suggestions
M_NO_SUGGESTIONS=Nessun Suggerimento

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Impostazioni del Correttore

#Example
W_001=Esempio

#Copy
W_COPY=Copia

#Cut
W_CUT=Tagliare

#Dictionary
W_DICTIONARY=Dizionario

#Enable
W_ENABLE=Attivare

#Ignore
W_IGNORE=Ignorare

#Paste
W_PASTE=Cartelle

#Redo
W_REDO=Rifare

#Undo
W_UNDO=Disfare