#You can add and/or remove words directly in the file
M_001=ファイルに直接単語を追加および/または削除することができます

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=単語は<b>改行</b>で区切る必要があります。つまり、<b>1行に1単語</b>です

#Open dictionary of words
M_003=言葉のオープン辞書

#Spell Check
M_004=スペルチェック

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>スペルチェッカー</b>は不正確な単語と文の最初の単語が小文字で始まるかどうかを確認します

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=彼は<b>一致</b>、複数形、性別などを修正せず、単に<b>スペル</b>を修正します

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=この単語の新しい発生がプログラムの他の場所で正しいと見なされるため、辞書に単語を追加するときは注意してください。

#When you add a word to the dictionary, only the original word will be added
M_008=辞書に単語を追加すると、元の単語のみが追加されます

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>変種</i>は辞書に追加されるまで不正確と見なされ続けます

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=単語<b>LimaGiran</b>が辞書に追加されました

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=<b>limagiran</b>のような出現は不正確と見なされ続けます

#Add to dictionary
M_ADD_TO_DICTIONARY=辞書に追加します

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=任意の単語を大文字で始めることを許可します

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=改行後の小文字で単語をチェックしてください

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=句読点の後、小文字で単語をチェックしてください

#Disable Spell Check
M_DISABLE_SPELL_CHECK=スペルチェックを無効にする

#Enable Spell Check
M_ENABLE_SPELL_CHECK=スペルチェックを有効にします

#Ignore all
M_IGNORE_ALL=すべて無視

#No Suggestions
M_NO_SUGGESTIONS=提案なし

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=スペルチェック設定

#Example
W_001=例

#Copy
W_COPY=コピー

#Cut
W_CUT=切る

#Dictionary
W_DICTIONARY=辞書

#Enable
W_ENABLE=有効

#Ignore
W_IGNORE=無視

#Paste
W_PASTE=ペースト

#Redo
W_REDO=やり直す

#Undo
W_UNDO=und