#You can add and/or remove words directly in the file
M_001=Anda boleh menambah dan/atau mengeluarkan perkataan secara langsung dalam fail

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Perkataan perlu dipisahkan dengan <b>baris baru</b>, iaitu, <b>satu perkataan setiap baris<b/>

#Open dictionary of words
M_003=Buka kamus perkataan

#Spell Check
M_004=Pemeriksa Ejaan

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>Pemeriksa Ejaan</b> memeriksa perkataan yang salah dan perkataan yang bermula dengan huruf kecil di awal ayat

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Ia <b>tidak</b> membetulkan kesesuaian, jamak, jantina, dsb. hanya <b>ejaan</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Berhati-hati semasa menambah perkataan ke dalam kamus, kerana semua kejadian baru perkataan ini akan dianggap betul di mana-mana tempat lain dalam program

#When you add a word to the dictionary, only the original word will be added
M_008=Apabila menambah perkataan ke dalam kamus, hanya bentuk asal yang akan ditambah

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>Variasi</i> akan terus dianggap salah sehingga ia juga ditambah ke dalam kamus

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Perkataan <b>LimaGiran</b> telah ditambah ke dalam kamus

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Kejadian seperti <b>limagiran</b> akan terus dianggap salah

#Add to dictionary
M_ADD_TO_DICTIONARY=Tambah ke dalam kamus

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Benarkan mana-mana perkataan bermula dengan huruf besar

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Periksa perkataan dengan huruf kecil selepas baris baru

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Periksa perkataan dengan huruf kecil selepas tanda baca

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Nyahaktifkan Pemeriksa

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Aktifkan Pemeriksa

#Ignore all
M_IGNORE_ALL=Abaikan semua

#No Suggestions
M_NO_SUGGESTIONS=Tiada Cadangan

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Tetapan Pemeriksa

#Example
W_001=Contoh

#Copy
W_COPY=Salin

#Cut
W_CUT=Potong

#Dictionary
W_DICTIONARY=Kamus

#Enable
W_ENABLE=Aktifkan

#Ignore
W_IGNORE=Abaikan

#Paste
W_PASTE=Tampal

#Redo
W_REDO=Ulang semula

#Undo
W_UNDO=Buat semula