#You can add and/or remove words directly in the file
M_001=U kunt woorden rechtstreeks in het bestand toevoegen en/of verwijderen

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Woorden moeten worden gescheiden door <b>regel afbreking</b>, dat wil zeggen, <b>één woord per regel <b />

#Open dictionary of words
M_003=Open woordenboek

#Spell Check
M_004=Spellingscontrole

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=De <b>Spellingscontrole</b> Checkt voor verkeerd gespelde woorden en woorden die beginnen met kleine letters

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Het <b>verhelpt geen</b> concordantie, meervoud, geslacht, enz. alleen <b>spelling</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Wees voorzichtig bij het toevoegen van woorden aan het woordenboek, want elke keer dat dit woord voorkomt in het programma zal het als correct wordt gezien

#When you add a word to the dictionary, only the original word will be added
M_008=Wanneer u een woord aan het woordenboek toevoegt, wordt alleen het originele woord toegevoegd

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=De <i>-variaties</i> zullen als onjuist worden beschouwd totdat ze ook aan het woordenboek worden toegevoegd

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Het woord <b>Limagiran</b> is toegevoegd aan het woordenboek

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Optredende woorden zoals <b>Limagiran</b> blijven als onjuist worden beschouwd

#Add to dictionary
M_ADD_TO_DICTIONARY=Toevoegen aan woordenboek

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Sta toe elk woord met een hoofdletter te beginnen

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Controleer het woord met kleine letter na een regel-afbreking

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Controleer het woord met kleine letter na leestekens

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Schakel Spellingcontrole uit

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Spellingcontrole inschakelen

#Ignore all
M_IGNORE_ALL=Negeer alles

#No Suggestions
M_NO_SUGGESTIONS=Geen suggesties

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Spellingscontrole-instellingen

#Example
W_001=Voorbeeld

#Copy
W_COPY=Kopiëren

#Cut
W_CUT=Knippen

#Dictionary
W_DICTIONARY=Woordenboek

#Enable
W_ENABLE=Inschakelen

#Ignore
W_IGNORE=Negeren

#Paste
W_PASTE=Plakken

#Redo
W_REDO=Opnieuw doen

#Undo
W_UNDO=Ongedaan maken