#You can add and/or remove words directly in the file
M_001=Możesz dodać i/lub usunąć słowa bezpośrednio w pliku

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Słowa powinny być oddzielone <b>nową linią</b>, to znaczy <b>jedno słowo na linię</b>

#Open dictionary of words
M_003=Otwórz słownik słów

#Spell Check
M_004=Korektor ortograficzny

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>Korektor ortograficzny</b> sprawdza niepoprawne słowa i słowa rozpoczynające zdanie małą literą

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=On <b>nie</b> poprawia zgodności, liczby, rodzaju itp., tylko <b>ortografię</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Uwaga przy dodawaniu słów do słownika, ponieważ wszystkie nowe wystąpienia tego słowa będą uważane za poprawne w każdym innym miejscu programu

#When you add a word to the dictionary, only the original word will be added
M_008=Dodając słowo do słownika, tylko oryginalna forma zostanie dodana

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>Wariacje</i> będą nadal uważane za niepoprawne, dopóki nie zostaną również dodane do słownika

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Słowo <b>LimaGiran</b> zostało dodane do słownika

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Wystąpienia takie jak <b>limagiran</b> będą nadal uważane za niepoprawne

#Add to dictionary
M_ADD_TO_DICTIONARY=Dodaj do słownika

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Zezwól, aby każde słowo zaczynało się wielką literą

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Sprawdź słowo zaczynające się małą literą po złamaniu linii

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Sprawdź słowo zaczynające się małą literą po interpunkcji

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Dezaktywować korektor

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Aktywować korektor

#Ignore all
M_IGNORE_ALL=Ignoruj wszystko

#No Suggestions
M_NO_SUGGESTIONS=Brak sugestii

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Ustawienia korektora

#Example
W_001=Przykład

#Copy
W_COPY=Kopiuj

#Cut
W_CUT=Przyciąć

#Dictionary
W_DICTIONARY=Słownik

#Enable
W_ENABLE=Aktywować

#Ignore
W_IGNORE=Ignoruj

#Paste
W_PASTE=Wklej

#Redo
W_REDO=Cofnij

#Undo
W_UNDO=Cofnij