#You can add and/or remove words directly in the file
M_001=Puteți adăuga și/sau elimina cuvinte direct în fișier

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Cuvintele trebuie să fie separate prin <b>linie nouă</b>, adică <b>un cuvânt pe linie</b>

#Open dictionary of words
M_003=Deschideți dicționarul de cuvinte

#Spell Check
M_004=Corector ortografic

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>Corectorul ortografic</b> verifică cuvintele incorecte și cuvintele care încep fraza cu literă mică

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=El <b>nu</b> corectează concordanța, pluralul, genul etc. doar <b>ortografia</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Atenție la adăugarea cuvintelor în dicționar, deoarece toate noile apariții ale acestui cuvânt vor fi considerate corecte în orice alt loc din program

#When you add a word to the dictionary, only the original word will be added
M_008=Când adăugați un cuvânt în dicționar, doar forma originală va fi adăugată

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=Variatiile <i>vor continua</i> să fie considerate incorecte până când vor fi adăugate și în dicționar

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Cuvântul <b>LimaGiran</b> a fost adăugat în dicționar

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Aparițiile precum <b>limagiran</b> vor continua să fie considerate incorecte

#Add to dictionary
M_ADD_TO_DICTIONARY=Adăugați în dicționar

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Permiteți ca orice cuvânt să înceapă cu literă mare

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Verificați cuvântul cu literă mică după linia nouă

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Verificați cuvântul cu literă mică după punctuație

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Dezactivați corectorul

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Activare corector

#Ignore all
M_IGNORE_ALL=Ignorare tot

#No Suggestions
M_NO_SUGGESTIONS=Fără sugestii

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Setări corector

#Example
W_001=Exemplu

#Copy
W_COPY=Copiere

#Cut
W_CUT=Decupare

#Dictionary
W_DICTIONARY=Dicționar

#Enable
W_ENABLE=Activare

#Ignore
W_IGNORE=Ignorare

#Paste
W_PASTE=Lipire

#Redo
W_REDO=Refacere

#Undo
W_UNDO=Anulare