#You can add and/or remove words directly in the file
M_001=நீங்கள் கோப்பில் நேரடியாக வார்த்தைகளை சேர்க்கவும் மற்றும்/அல்லது நீக்கவும் முடியும்

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=வார்த்தைகள் <b>வரிசை இடைவெளி</b> மூலம் பிரிக்கப்பட வேண்டும், அதாவது <b>ஒரு வார்த்தை ஒரு வரியில்</b>

#Open dictionary of words
M_003=வார்த்தைகளின் அகராதியை திறக்கவும்

#Spell Check
M_004=எழுத்துப்பிழை சரிபார்ப்பாளர்

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>எழுத்துப்பிழை சரிபார்ப்பாளர்</b> தவறான வார்த்தைகள் மற்றும் வாக்கியத்தின் தொடக்கத்தில் சிறிய எழுத்தால் தொடங்கும் வார்த்தைகளை சரிபார்க்கிறது

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=அவர் <b>சரிசெய்யவில்லை</b> ஒத்திசைவு, பன்மை, பாலினம், மற்றும் இதரங்களை, வெறும் <b>எழுத்துப்பிழை</b> மட்டுமே

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=அகராதியில் வார்த்தைகளைச் சேர்க்கும்போது, அந்த வார்த்தையின் அனைத்து புதிய நிகழ்வுகளும் நிரலின் மற்ற இடங்களில் சரியானதாகக் கருதப்படும்

#When you add a word to the dictionary, only the original word will be added
M_008=ஒரு வார்த்தையை அகராதியில் சேர்க்கும்போது, வெறும் அசல் வடிவமே சேர்க்கப்படும்

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>மாறுபாடுகள்</i> அகராதியில் சேர்க்கப்படும் வரை தவறானதாகக் கருதப்படும்

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=<b>LimaGiran</b> என்ற வார்த்தை அகராதிக்கு சேர்க்கப்பட்டுள்ளது

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=<b>limagiran</b> போன்ற நிகழ்வுகள் தவறானதாகக் கருதப்படும்

#Add to dictionary
M_ADD_TO_DICTIONARY=அகராதிக்கு சேர்க்கவும்

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=எந்தவொரு வார்த்தையும் பெரிய எழுத்தால் தொடங்க அனுமதிக்கவும்

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=வரிசை இடைவெளிக்குப் பிறகு சிறிய எழுத்தால் தொடங்கும் வார்த்தையை சரிபார்க்கவும்

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=அணிகூட்டத்திற்குப் பிறகு சிறிய எழுத்தால் தொடங்கும் வார்த்தையை சரிபார்க்கவும்

#Disable Spell Check
M_DISABLE_SPELL_CHECK=சரிபார்ப்பாளரை முடக்கவும்

#Enable Spell Check
M_ENABLE_SPELL_CHECK=சரிபார்ப்பாளரை செயல்படுத்தவும்

#Ignore all
M_IGNORE_ALL=எல்லாவற்றையும் புறக்கணிக்கவும்

#No Suggestions
M_NO_SUGGESTIONS=எந்தவொரு பரிந்துரைகளும் இல்லை

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=சரிபார்ப்பாளர் அமைப்புகள்

#Example
W_001=எடுத்துக்காட்டு

#Copy
W_COPY=பகிரவும்

#Cut
W_CUT=கீறி

#Dictionary
W_DICTIONARY=அகராதி

#Enable
W_ENABLE=செயல்படுத்தவும்

#Ignore
W_IGNORE=புறக்கணிக்கவும்

#Paste
W_PASTE=ஒட்டவும்

#Redo
W_REDO=மீண்டும் செய்யவும்

#Undo
W_UNDO=மீட்டமை