#You can add and/or remove words directly in the file
M_001=మీరు పదాలను నేరుగా ఫైలులో చేర్చవచ్చు మరియు/లేదా తొలగించవచ్చు

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=పదాలను <b>రేఖ విరామం</b> ద్వారా వేరుచేయాలి, అంటే <b>ఒక పదం ఒక పంక్తి<b/>

#Open dictionary of words
M_003=పదాల నిఘంటువును తెరవండి

#Spell Check
M_004=అక్షరరూప సరిదిద్దుడు

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>అక్షరరూప సరిదిద్దుడు</b> తప్పు పదాలు మరియు చిన్న అక్షరంతో వాక్యం ప్రారంభమయ్యే పదాలను తనిఖీ చేస్తుంది

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=అతను <b>సరిదిద్దడం</b>, బహువచనం, లింగం మొదలైన వాటిని సరిదిద్దదు, కేవలం <b>అక్షరరూపం</b> మాత్రమే

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=నిఘంటువులో పదాలను చేర్చేటప్పుడు జాగ్రత్తగా ఉండండి, ఎందుకంటే ఈ పదం యొక్క అన్ని కొత్త సంభవాలు ప్రోగ్రామ్‌లో ఎక్కడైనా సరైనవి అని పరిగణించబడతాయి

#When you add a word to the dictionary, only the original word will be added
M_008=నిఘంటువులో పదాన్ని చేర్చేటప్పుడు, కేవలం అసలు రూపం మాత్రమే చేర్చబడుతుంది

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>వేరియేషన్లు</i> కూడా నిఘంటువులో చేర్చబడే వరకు తప్పుగా పరిగణించబడుతాయి

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=పదం <b>LimaGiran</b> నిఘంటువులో చేర్చబడింది

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=<b>limagiran</b> వంటి సంభవాలు తప్పుగా పరిగణించబడుతూనే ఉంటాయి

#Add to dictionary
M_ADD_TO_DICTIONARY=నిఘంటువులో చేర్చండి

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=ఏదైనా పదం పెద్ద అక్షరంతో ప్రారంభమవ్వడానికి అనుమతించండి

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=రేఖ విరామం తర్వాత చిన్న అక్షరంతో పదాన్ని తనిఖీ చేయండి

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=పంక్తి తర్వాత చిన్న అక్షరంతో పదాన్ని తనిఖీ చేయండి

#Disable Spell Check
M_DISABLE_SPELL_CHECK=సరిదిద్దును నిలిపివేయండి

#Enable Spell Check
M_ENABLE_SPELL_CHECK=సరిదిద్దును ప్రారంభించండి

#Ignore all
M_IGNORE_ALL=అన్నీ పక్కన పెట్టండి

#No Suggestions
M_NO_SUGGESTIONS=సూచనలు లేవు

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=సరిదిద్దుని సెట్టింగులు

#Example
W_001=ఉదాహరణ

#Copy
W_COPY=కాపీ చేయండి

#Cut
W_CUT=కత్తిరించండి

#Dictionary
W_DICTIONARY=నిఘంటువు

#Enable
W_ENABLE=చాలన చేయండి

#Ignore
W_IGNORE=పక్కన పెట్టండి

#Paste
W_PASTE=కాపీ చేయండి

#Redo
W_REDO=మరలా చేయండి

#Undo
W_UNDO=తిరిగి చేయండి