#You can add and/or remove words directly in the file
M_001=คุณสามารถเพิ่มและ/หรือลบคำโดยตรงในไฟล์ได้

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=คำจะต้องแยกออกจากกันด้วย <b>การขึ้นบรรทัดใหม่</b> หรือ <b>คำหนึ่งคำต่อหนึ่งบรรทัด<b/>

#Open dictionary of words
M_003=เปิดพจนานุกรมคำ

#Spell Check
M_004=ตัวตรวจสอบการสะกด

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>ตัวตรวจสอบการสะกด</b> ตรวจสอบคำที่ไม่ถูกต้องและคำที่เริ่มต้นประโยคด้วยตัวอักษรตัวเล็ก

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=มัน <b>ไม่</b> แก้ไขความสอดคล้อง, พหูพจน์, เพศ, ฯลฯ เพียงแค่ <b>การสะกด</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=โปรดระมัดระวังเมื่อเพิ่มคำลงในพจนานุกรม เนื่องจากการเกิดขึ้นใหม่ทั้งหมดของคำนี้จะถือว่าถูกต้องในที่อื่น ๆ ของโปรแกรม

#When you add a word to the dictionary, only the original word will be added
M_008=เมื่อเพิ่มคำลงในพจนานุกรม จะมีเพียงรูปแบบดั้งเดิมเท่านั้นที่จะถูกเพิ่มเข้าไป

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>ความแปรผัน</i> จะยังคงถูกพิจารณาว่าไม่ถูกต้องจนกว่าพวกมันจะถูกเพิ่มลงในพจนานุกรมด้วย

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=คำว่า <b>LimaGiran</b> ได้ถูกเพิ่มลงในพจนานุกรมแล้ว

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=การเกิดขึ้นเช่น <b>limagiran</b> จะยังคงถูกพิจารณาว่าไม่ถูกต้อง

#Add to dictionary
M_ADD_TO_DICTIONARY=เพิ่มลงในพจนานุกรม

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=อนุญาตให้คำใด ๆ เริ่มต้นด้วยตัวอักษรตัวใหญ่

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=ตรวจสอบคำที่มีตัวอักษรตัวเล็กหลังจากการขึ้นบรรทัดใหม่

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=ตรวจสอบคำที่มีตัวอักษรตัวเล็กหลังจากเครื่องหมายวรรคตอน

#Disable Spell Check
M_DISABLE_SPELL_CHECK=ปิดการใช้งานตัวตรวจสอบ

#Enable Spell Check
M_ENABLE_SPELL_CHECK=เปิดใช้งานตัวตรวจสอบ

#Ignore all
M_IGNORE_ALL=ข้ามทั้งหมด

#No Suggestions
M_NO_SUGGESTIONS=ไม่มีข้อเสนอแนะ

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=การตั้งค่าของตัวตรวจสอบ

#Example
W_001=ตัวอย่าง

#Copy
W_COPY=คัดลอก

#Cut
W_CUT=ตัด

#Dictionary
W_DICTIONARY=พจนานุกรม

#Enable
W_ENABLE=เปิดใช้งาน

#Ignore
W_IGNORE=ข้าม

#Paste
W_PASTE=วาง

#Redo
W_REDO=ทำใหม่

#Undo
W_UNDO=เลิกทำ