#You can add and/or remove words directly in the file
M_001=Maaari mong idagdag at/o alisin ang mga salita nang direkta sa file

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Ang mga salita ay dapat na paghiwalayin ng <b>pagputol ng linya</b>, ibig sabihin, <b>isang salita bawat linya<b/>

#Open dictionary of words
M_003=Buksan ang diksiyonaryo ng mga salita

#Spell Check
M_004=Tamang Baybay

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=Ang <b>Tamang Baybay</b> ay sumusuri ng mga maling salita at mga salita na nagsisimula sa pangungusap na may maliit na titik

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Siya <b>hindi</b> nagwawasto ng pagkakasundo, plural, kasarian, atbp. tanging <b>baybay</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Mag-ingat sa pagdaragdag ng mga salita sa diksiyonaryo, dahil lahat ng bagong pagkakataon ng salitang ito ay ituturing na tama sa anumang ibang bahagi ng programa

#When you add a word to the dictionary, only the original word will be added
M_008=Kapag nagdagdag ka ng isang salita sa diksiyonaryo, tanging ang orihinal na anyo lamang ang idaragdag

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=Ang mga <i>baryasyon</i> ay patuloy na ituturing na mali hanggang sa sila rin ay maidagdag sa diksiyonaryo

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Ang salitang <b>LimaGiran</b> ay naidagdag sa diksiyonaryo

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Ang mga pagkakataon tulad ng <b>limagiran</b> ay patuloy na ituturing na mali

#Add to dictionary
M_ADD_TO_DICTIONARY=Idagdag sa diksiyonaryo

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Payagan ang anumang salita na magsimula sa malaking titik

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Suriin ang salita na may maliit na titik pagkatapos ng pagputol ng linya

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Suriin ang salita na may maliit na titik pagkatapos ng bantas

#Disable Spell Check
M_DISABLE_SPELL_CHECK=I-disable ang Tamang Baybay

#Enable Spell Check
M_ENABLE_SPELL_CHECK=I-activate ang Tamang Baybay

#Ignore all
M_IGNORE_ALL=Balewalain ang lahat

#No Suggestions
M_NO_SUGGESTIONS=Walang Mga Suhestiyon

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Mga Setting ng Tamang Baybay

#Example
W_001=Halimbawa

#Copy
W_COPY=Kopyahin

#Cut
W_CUT=I-cut

#Dictionary
W_DICTIONARY=Diksiyonaryo

#Enable
W_ENABLE=I-activate

#Ignore
W_IGNORE=Balewalain

#Paste
W_PASTE=I-paste

#Redo
W_REDO=Gawin muli

#Undo
W_UNDO=I-undo