#You can add and/or remove words directly in the file
M_001=Kelimeyi doğrudan dosyaya ekleyebilir ve/veya kaldırabilirsiniz

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Kelimeler <b>satır sonu</b> ile ayrılmalıdır, yani <b>her satıra bir kelime</b>

#Open dictionary of words
M_003=Kelime sözlüğünü aç

#Spell Check
M_004=Yazım Denetleyici

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>Yazım Denetleyici</b> yanlış kelimeleri ve cümle başlangıcında küçük harfle başlayan kelimeleri kontrol eder

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=O <b>doğru</b> dil bilgisi, çoğul, cinsiyet vb. düzeltmez, sadece <b>yazım</b> düzeltir

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Sözlüğe kelime eklerken dikkatli olun, çünkü bu kelimenin tüm yeni kullanımları programın başka yerlerinde doğru olarak kabul edilecektir

#When you add a word to the dictionary, only the original word will be added
M_008=Sözlüğe bir kelime eklerken yalnızca orijinal şekli eklenecektir

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=İçinde <i>varyasyonlar</i> bulunan kelimeler, sözlüğe eklenene kadar yanlış olarak kabul edilmeye devam edecektir

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Kelime <b>LimaGiran</b> sözlüğe eklendi

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=<b>limagiran</b> gibi kullanımlar yanlış olarak kabul edilmeye devam edecektir

#Add to dictionary
M_ADD_TO_DICTIONARY=Sözlüğe ekle

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Herhangi bir kelimenin büyük harfle başlamasına izin ver

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Satır sonundan sonra küçük harfle başlayan kelimeyi kontrol et

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Noktalama işaretinden sonra küçük harfle başlayan kelimeyi kontrol et

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Yazım Denetleyiciyi devre dışı bırak

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Yazım Denetleyiciyi Etkinleştir

#Ignore all
M_IGNORE_ALL=Her şeyi yoksay

#No Suggestions
M_NO_SUGGESTIONS=Öneri yok

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Yazım Denetleyici Ayarları

#Example
W_001=Örnek

#Copy
W_COPY=Kopyala

#Cut
W_CUT=Kes

#Dictionary
W_DICTIONARY=Sözlük

#Enable
W_ENABLE=Etkinleştir

#Ignore
W_IGNORE=Yoksay

#Paste
W_PASTE=Yapıştır

#Redo
W_REDO=Yeniden yap

#Undo
W_UNDO=Geri al