#You can add and/or remove words directly in the file
M_001=Ви можете додавати та/або видаляти слова безпосередньо в файлі

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Слова повинні бути розділені <b>переносом рядка</b>, тобто <b>одне слово на рядок<b/>

#Open dictionary of words
M_003=Відкрити словник

#Spell Check
M_004=Перевірка правопису

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>Перевірка Правопису</b> перевіряє неправильні слова та початкові слова, що починаються з маленької літери

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Це <b>не</b> виправляє узгодження, множину, рід тощо, лише <b>правопис</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Будьте обережні при додаванні слів до словника, оскільки всі нові випадки цього слова будуть вважатися правильними в будь-якому іншому місці програми

#When you add a word to the dictionary, only the original word will be added
M_008=При додаванні слова до словника, буде додано лише вихідне слово

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>Варіації</i> будуть вважатися неправильними, поки вони також не будуть додані до словника

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Слово <b>LimaGiran</b> було додано до словника

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Випадки, як <b>limagiran</b>, будуть вважатися неправильними

#Add to dictionary
M_ADD_TO_DICTIONARY=Додати до словника

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Дозволити будь-якому слову починатися з великої літери

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Перевірте слово з маленької літери після переносу рядка

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Перевірте слово з маленької літери після пунктуації

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Вимкнути перевірку правопису

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Ввімкнути перевірку правопису

#Ignore all
M_IGNORE_ALL=Ігнорувати все

#No Suggestions
M_NO_SUGGESTIONS=Без пропозицій

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Налаштування перевірки правопису

#Example
W_001=Приклад

#Copy
W_COPY=Копіювати

#Cut
W_CUT=Вирізати

#Dictionary
W_DICTIONARY=Словник

#Enable
W_ENABLE=Ввімкнути

#Ignore
W_IGNORE=Ігнорувати

#Paste
W_PASTE=Вставити

#Redo
W_REDO=Повторити

#Undo
W_UNDO=Скасувати