#You can add and/or remove words directly in the file
M_001=آپ براہ راست فائل میں الفاظ شامل اور/یا ہٹا سکتے ہیں

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=الفاظ کو <b>نئی لائن</b> سے الگ کیا جانا چاہیے، یعنی <b>ایک لفظ فی لائن</b>

#Open dictionary of words
M_003=الفاظ کی لغت کھولیں

#Spell Check
M_004=ہجے کی جانچ کرنے والا

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>ہجے کی جانچ کرنے والا</b> غلط الفاظ اور جملے کے آغاز میں چھوٹے حرف سے الفاظ کی جانچ کرتا ہے

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=یہ <b>نہیں</b> درست کرتا ہم آہنگی، جمع، جنس، وغیرہ صرف <b>ہجے</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=لغت میں الفاظ شامل کرتے وقت توجہ دیں، کیونکہ اس لفظ کے تمام نئے واقعات پروگرام کے کسی اور جگہ پر درست سمجھے جائیں گے

#When you add a word to the dictionary, only the original word will be added
M_008=لغت میں ایک لفظ شامل کرتے وقت صرف اصل شکل شامل کی جائے گی

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=<i>تبدیلیاں</i> غلط سمجھی جائیں گی جب تک کہ انہیں بھی لغت میں شامل نہ کیا جائے

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=لفظ <b>LimaGiran</b> لغت میں شامل کیا گیا ہے

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=واقعات جیسے <b>limagiran</b> غلط سمجھے جائیں گے

#Add to dictionary
M_ADD_TO_DICTIONARY=لغت میں شامل کریں

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=کسی بھی لفظ کا آغاز بڑے حرف سے کرنے کی اجازت دیں

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=نئی لائن کے بعد چھوٹے حرف سے لفظ کی جانچ کریں

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=نقطہ کے بعد چھوٹے حرف سے لفظ کی جانچ کریں

#Disable Spell Check
M_DISABLE_SPELL_CHECK=ہجے کی جانچ کو غیر فعال کریں

#Enable Spell Check
M_ENABLE_SPELL_CHECK=ہجے کی جانچ کو چالو کریں

#Ignore all
M_IGNORE_ALL=سب کچھ نظر انداز کریں

#No Suggestions
M_NO_SUGGESTIONS=کوئی تجاویز نہیں

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=ہجے کی جانچ کی ترتیبات

#Example
W_001=مثال

#Copy
W_COPY=نقل کریں

#Cut
W_CUT=کٹائیں

#Dictionary
W_DICTIONARY=لغت

#Enable
W_ENABLE=چالو کریں

#Ignore
W_IGNORE=نظر انداز کریں

#Paste
W_PASTE=چسپاں کریں

#Redo
W_REDO=دوبارہ کریں

#Undo
W_UNDO=کچھ واپس کریں