#You can add and/or remove words directly in the file
M_001=Bạn có thể thêm và/hoặc xóa từ trực tiếp trong tệp

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Các từ phải được tách biệt bằng <b>xuống dòng</b>, tức là <b>một từ mỗi dòng</b>

#Open dictionary of words
M_003=Mở từ điển từ

#Spell Check
M_004=Trình kiểm tra chính tả

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=Trình <b>kiểm tra chính tả</b> kiểm tra các từ không đúng và các từ bắt đầu câu bằng chữ cái viết thường

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=Nó <b>không</b> sửa lỗi ngữ pháp, số nhiều, giới tính, v.v. chỉ <b>chính tả</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Chú ý khi thêm từ vào từ điển, vì tất cả các trường hợp mới của từ này sẽ được coi là đúng ở bất kỳ nơi nào khác trong chương trình

#When you add a word to the dictionary, only the original word will be added
M_008=Khi thêm một từ vào từ điển, chỉ hình thức gốc sẽ được thêm vào

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=Các <i>biến thể</i> sẽ tiếp tục được coi là không đúng cho đến khi chúng cũng được thêm vào từ điển

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Từ <b>LimaGiran</b> đã được thêm vào từ điển

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Các trường hợp như <b>limagiran</b> sẽ tiếp tục được coi là không đúng

#Add to dictionary
M_ADD_TO_DICTIONARY=Thêm vào từ điển

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Cho phép bất kỳ từ nào bắt đầu bằng chữ cái viết hoa

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Kiểm tra từ có chữ cái viết thường sau khi xuống dòng

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Kiểm tra từ có chữ cái viết thường sau dấu câu

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Tắt trình kiểm tra

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Kích hoạt trình kiểm tra

#Ignore all
M_IGNORE_ALL=Bỏ qua tất cả

#No Suggestions
M_NO_SUGGESTIONS=Không có gợi ý

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Cài đặt của trình kiểm tra

#Example
W_001=Ví dụ

#Copy
W_COPY=Sao chép

#Cut
W_CUT=Cắt

#Dictionary
W_DICTIONARY=Từ điển

#Enable
W_ENABLE=Kích hoạt

#Ignore
W_IGNORE=Bỏ qua

#Paste
W_PASTE=Dán

#Redo
W_REDO=Làm lại

#Undo
W_UNDO=Hoàn tác