#You can add and/or remove words directly in the file
M_001=O le fi kun ati/tabi yọ awọn ọrọ taara ninu faili

#Words must be separated by <b>line break</b>, that is, <b>one word per line<b/>
M_002=Awọn ọrọ gbọdọ wa ni pin nipasẹ <b>iyipada ila</b>, iyẹn ni, <b>ọrọ kan fun ila<b/>

#Open dictionary of words
M_003=Ṣii ọrọ-ọrọ ti awọn ọrọ

#Spell Check
M_004=Oluyẹwo Ìkọ̀wé

#The <b>Spell Checker</b> checks for misspelled words and lowercase start words
M_005=<b>Oluyẹwo Ìkọ̀wé</b> n ṣayẹwo awọn ọrọ ti ko tọ ati awọn ọrọ ti o bẹrẹ gbolohun pẹlu lẹta kekere

#It <b>does not</b> fix concordance, plural, gender, etc. only <b>spelling</b>
M_006=O <b>ko</b> ṣe atunṣe ibamu, plural, irú, ati bẹbẹ lọ, nikan <b>ìkọ̀wé</b>

#Be careful when adding words to the dictionary, since all new occurrences of this word will be considered correct elsewhere in the program
M_007=Ṣọra nigbati o ba nfi awọn ọrọ kun si ọrọ-ọrọ, nitori gbogbo awọn iṣẹlẹ tuntun ti ọrọ yii yoo jẹ akiyesi bi o tọ ni eyikeyi ibi miiran ti eto naa

#When you add a word to the dictionary, only the original word will be added
M_008=Nigbati o ba nfi ọrọ kan kun si ọrọ-ọrọ, nikan fọọmu atilẹba ni yoo fi kun

#The <i>variations</i> will continue to be considered incorrect until they are also added to the dictionary
M_009=Awọn <i>iyipada</i> yoo tẹsiwaju lati jẹ akiyesi bi ko tọ titi ti wọn yoo fi tun fi kun si ọrọ-ọrọ

#The word <b>LimaGiran</b> has been added to the dictionary
M_010=Ọrọ <b>LimaGiran</b> ti fi kun si ọrọ-ọrọ

#Occurrences like <b>limagiran</b> will continue to be considered incorrect
M_011=Awọn iṣẹlẹ bi <b>limagiran</b> yoo tẹsiwaju lati jẹ akiyesi bi ko tọ

#Add to dictionary
M_ADD_TO_DICTIONARY=Fi kun si ọrọ-ọrọ

#Allow any word to start with a capital letter
M_ALLOW_ANY_WORD_FIRST_UPPER=Jẹ ki eyikeyi ọrọ bẹrẹ pẹlu lẹta nla

#Check word with lowercase letter after line break
M_CHECK_WORD_WITH_LOWER_AFTER_LINE_BREAK=Ṣayẹwo ọrọ pẹlu lẹta kekere lẹhin iyipada ila

#Check word with lowercase letter after punctuation
M_CHECK_WORD_WITH_LOWER_AFTER_PUNCTUATION=Ṣayẹwo ọrọ pẹlu lẹta kekere lẹhin ami idasilẹ

#Disable Spell Check
M_DISABLE_SPELL_CHECK=Pa Oluyẹwo

#Enable Spell Check
M_ENABLE_SPELL_CHECK=Mú Oluyẹwo ṣiṣẹ

#Ignore all
M_IGNORE_ALL=Foju kọ gbogbo rẹ

#No Suggestions
M_NO_SUGGESTIONS=Ko si Awọn imọran

#Spell Check Settings
M_SPELL_CHECK_SETTINGS=Awọn eto Oluyẹwo

#Example
W_001=Apẹẹrẹ

#Copy
W_COPY=Daakọ

#Cut
W_CUT=Ge

#Dictionary
W_DICTIONARY=Ọrọ-ọrọ

#Enable
W_ENABLE=Mú ṣiṣẹ

#Ignore
W_IGNORE=Foju kọ

#Paste
W_PASTE=Daakọ

#Redo
W_REDO=Tun ṣe

#Undo
W_UNDO=Ṣe atunṣe